### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by legabiMC** [Enishowk/Bot-Discord#9]
I wan't to use your code but when I try to start the bot (node src/bot.js because I don't want to use pm2) I have this error :

node src/bot.js

internal/modules/cjs/loader.js:723
    throw err;
    ^

SyntaxError: C:\Users\savelec\Bot-Discord\config\config.json: Unexpected token }
 in JSON at position 213
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:720:27)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\savelec\Bot-Discord\src\bot.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)

I search on the net but nothing work :/

I wait your answer :)
legabiMC

**Comment by Enishowk** [comment]
Hello,

I think you have a problem with your `config.json` file. You can put its content [here](https://jsonlint.com/) for example to check that it is valid. I think it's because of the last comma : [this line.](https://github.com/Enishowk/Bot-Discord/blob/master/config/config.json.dist#L6)

**Comment by legabiMC** [comment]
It works ! Thank you very much ^^

This doesn't work : 

{
  "token": "yourToken",
  "startCommand": ".",
  "userAdmin": "yourId",
  "nsfwChan": "nsfwChanId",
  "guildID": "guildID",
}

But this work : 

{
  "token": "yourToken",
  "startCommand": ".",
  "userAdmin": "yourId",
  "nsfwChan": "nsfwChanId",
  "guildID": "guildID"} <-- HERE

Delete , and replace by }

Thank you for helping me ^^
legabiMC

**Comment by legabiMC** [comment]
Je galérais à parler anglais mais je viens de voir que vous êtes français x)

Merci de l'aide rapide ^^

**Comment by Enishowk** [comment]
En effet, mais ça permet à d'autres de suivre si jamais.

Pas de soucis. ;)

**Comment by legabiMC** [comment]
J'ai une autre question ^^' (Pas de rapport avec le sujet mais promis c'est la dernière)

Avez vous un Discord que je pourrais rejoindre pour poser des questions plus facilement, avoir des conseils ou même voir les dernières news du bot ?

Merci d'avance pour votre réponse :)
legabiMC
